name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'

env:
  BUILD_TYPE: Release
  PROJECT_NAME: plugify-source2-launcher

jobs:
  setup:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      github_sha_short: ${{ steps.vars.outputs.github_sha_short }}
    steps:
      - name: Set variables
        id: vars
        run: echo "github_sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Generate Release
        if: ${{ !env.ACT }}
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  build:
    needs: setup
    if: ${{ needs.setup.outputs.release_created }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win64
            arch: x64
            container: null
            setup_env: msvc
            cmake_flags: ""
            project_name: plugify-source2-launcher
          - os: ubuntu-latest
            platform: linuxsteamrt64
            arch: x86_64
            container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
            setup_env: gcc14
            cmake_flags: ""
            project_name: plugify-source2-launcher
          - os: ubuntu-latest
            platform: linuxsteamrt64
            arch: x86_64
            container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
            setup_env: gcc14
            cmake_flags: "-DS2_LAUNCHER=ON"
            project_name: plugify-source2-launcher-server
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Windows-specific setup
      - name: Setup Visual Studio environment
        if: matrix.setup_env == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # Linux-specific setup (in container)
      - name: Install GCC-14
        if: matrix.setup_env == 'gcc14'
        shell: bash -el {0}
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-14-monolithic
          ln -sf /usr/bin/gcc-14 /usr/bin/gcc && ln -sf /usr/bin/g++-14 /usr/bin/g++
        # for ACT add nodejs

      - name: Setup CMake
        if: matrix.setup_env == 'msvc'
        uses: lukka/get-cmake@latest

      - name: Cache build dependencies
        if: matrix.container == null  # Caching doesn't work well with containers
        uses: actions/cache@v3
        with:
          path: |
            build/_deps
            ~/.vcpkg
            ~/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure
        shell: bash -el {0}
        run: |
          cmake -S . -B build -G "Ninja" -DS2_VERSION="${{ needs.setup.outputs.tag_name }}" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${{ matrix.cmake_flags }}

      - name: Build
        shell: bash -el {0}
        run: |
          cmake --build build --target ${{ env.PROJECT_NAME }} --config ${{ env.BUILD_TYPE }} --parallel

      - name: Prepare artifacts
        shell: bash -el {0}
        run: |
          mkdir -p build/output/bin/${{ matrix.platform }}/
          mkdir -p build/output/csgo/bin/${{ matrix.platform }}/
          cp build/external/plugify/*plugify.* build/output/bin/${{ matrix.platform }}/
          cp build/external/sentry/*sentry.* build/output/bin/${{ matrix.platform }}/
          if [[ "${{ matrix.project_name }}" = "${{ env.PROJECT_NAME }}-server" ]]; then
            cp build/*server_valve* build/output/csgo/bin/${{ matrix.platform }}/
          else
            cp build/*s2launcher* build/output/bin/${{ matrix.platform }}/
          fi
          cp build/external/sentry/crashpad_build/handler/crashpad_handler build/output/bin/${{ matrix.platform }}/
          cp build/sentry.jsonc build/output/bin/${{ matrix.platform }}/
          mkdir -p build/output/csgo/addons/plugify/bin/${{ matrix.platform }}/
          cp build/micromamba* build/output/csgo/addons/plugify/bin/${{ matrix.platform }}/
          # cp build/plugify.pconfig build/output/csgo
          # Cleanup dev files
          find build/output -type f \( -name "*.exp" -o -name "*.ilk" -o -name "*.lib" -o -name "*.pdb" \) -delete
    
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project_name }}-build-${{ matrix.platform }}-${{ needs.setup.outputs.github_sha_short }}
          path: build/output/
          retention-days: 7

  package:
    needs: ["setup", "build"]
    if: ${{ needs.setup.outputs.release_created }}
    strategy:
      matrix:
        include:
          - platform: win64
            project_name: plugify-source2-launcher
          - platform: linuxsteamrt64
            project_name: plugify-source2-launcher
          - platform: linuxsteamrt64
            project_name: plugify-source2-launcher-server
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.release.outputs.url }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.project_name }}-build-${{ matrix.platform }}-${{ needs.setup.outputs.github_sha_short }}
          path: artifacts/${{ matrix.platform }}

      - name: Compress build artifacts
        run: |
          mkdir -p build/${{ matrix.platform }}
          tar -cjf build/${{ matrix.platform }}/${{ matrix.project_name }}-build-${{ matrix.platform }}-${{ needs.setup.outputs.github_sha_short }}.tar.bz2 \
            -C artifacts/${{ matrix.platform }} .

      - name: Upload release asset
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v1
        id: release
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          files: |
            build/${{ matrix.platform }}/*.tar.bz2

  notify:
    needs: ["setup", "build", "package"]
    if: ${{ needs.setup.outputs.release_created && always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        if: ${{ needs.build.result == 'success' && needs.package.result == 'success' }}
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-description: |
            ## <:plugin_creator:1336096248515657880> New Release: ${{ env.PROJECT_NAME }} ${{ needs.setup.outputs.tag_name }}
      
            ### <:link:1342486300653129811> Downloads: [${{ needs.setup.outputs.tag_name }}](${{ needs.package.outputs.url }})
      
            ### Install via curl:
            **For Linux:**
            ```bash
            cd ./cs2/game
            curl -LO https://github.com/${{ github.repository }}/releases/download/${{ needs.setup.outputs.tag_name }}/${{ env.PROJECT_NAME }}-build-linuxsteamrt64-${{ needs.setup.outputs.github_sha_short }}.tar.bz2
            ```
            
            ### Install via curl:
            **For Linux (Alternative):**
            ```bash
            cd ./cs2/game
            curl -LO https://github.com/${{ github.repository }}/releases/download/${{ needs.setup.outputs.tag_name }}/${{ env.PROJECT_NAME }}-server-build-linuxsteamrt64-${{ needs.setup.outputs.github_sha_short }}.tar.bz2
            ```
      
            **For Windows:**
            ```bash
            cd ./cs2/game
            curl -LO https://github.com/${{ github.repository }}/releases/download/${{ needs.setup.outputs.tag_name }}/${{ env.PROJECT_NAME }}-build-win64-${{ needs.setup.outputs.github_sha_short }}.tar.bz2
            ```
          embed-color: 955135
      
      - name: Send Failure Notification
        if: ${{ needs.build.result == 'failure' || needs.package.result == 'failure' }}
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-description: |
            ## <a:cry:1247121995997384738> Release workflow failed for ${{ env.PROJECT_NAME }} ${{ needs.setup.outputs.tag_name }}
          embed-color: 16221227
